### ISSUE TITLE
KMControllersでティーチングで覚えた1動作のみの削除が行えない。

### ISSUE THREAD

**Issue by carrot-ishikawa** [keigan-motor/pykeigan_motor#3]
KMControllers.pyのeraseMotionメソッドを実行しても
KeiganMotorに記録した動作が削除されませんでした。

ソースを確認したところ、
送信するコマンドが「\xA4」となっています。
こちらのコマンドは、eraseAllTasksetメソッドと同じになっておりますため、
コマンドが間違っているのではないかと思われます。

正しくは「\xAD」ではないでしょうか？
試しに「\xAD」限りでは削除が行われているようです。

**Comment by wingcloud** [comment]
ご報告ありがとうございます。おっしゃるとおり\xADの間違いでした。
修正させていただきました。
